### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by GraemeWatt** [datacite/spinone#21]
I just started trying to use the DataCite REST API today.  It seems that the `rows` and `offset` parameters have no effect, with the response always using the default values of `rows=25` and `offset=0`.  This can be easily seen from a few examples given in the documentation:

https://api.datacite.org/works?query=cancer&rows=100
https://api.datacite.org/works?query=climate+-change&rows=1
https://api.datacite.org/works?query=allen+renear&rows=5
https://api.datacite.org/works?query=allen+renear&rows=0
https://api.datacite.org/works?query=allen+renear&rows=5&offset=5

or even from the web interface:

https://support.datacite.org/v1.1/reference#testinput

**Comment by mfenner** [comment]
@GraemeWatt we have changed the API to be compatible with the [JSONAPI spec](http://jsonapi.org/format/#fetching-pagination), but have not updated our documentation. Use `page[size]` instead of `rows` and `page[number]` instead of `offset` (obviously this is not the same thing). For example:

https://api.datacite.org/works?query=allen+renear&page[size]=5
https://api.datacite.org/works?query=allen+renear&page[size]=1 (page[size] = 0 is not supported)
https://api.datacite.org/works?query=allen+renear&page[size]=5&page[number]=2

**Comment by GraemeWatt** [comment]
@mfenner Thanks for the quick response.  It would be good to update the API documentation.

**Comment by GraemeWatt** [comment]
The change should also be propagated to [DataCite Search](https://github.com/datacite/search) where pagination is currently broken.  After entering a search query, the navigation links at the bottom of the page simply return the first page again, e.g. https://search.datacite.org/works?query=&page=2.

**Comment by mfenner** [comment]
Thanks @GraemeWatt. DataCite Search is fixed via https://github.com/datacite/datacite/issues/245.  And I have updated the documentation at https://support.datacite.org.
